config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'
  resources :questions, only: [:index, :show]
  resources :questions do
    member do
      post :answer # 回答を処理するルート
      get :result # 結果を表示するためのルート
      get :reason
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :questions
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :genre
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @genres = Genre.all
    if params[:genre_id].present?
      @questions = Question.where(genre_id: params[:genre_id])
    else
      @questions = Question.all
    end
  end

  def show
    @question = Question.find(params[:id])
  end

  def reason
    @question = Question.find(params[:id])
    @user_answer = params[:answer] # ユーザーの回答を保持
  end

  def answer
    @question = Question.find(params[:id])
    user_answer = params[:answer]
    @correct = user_answer == @question.correct_answer # 正誤判定
    render :result
  end

  def result
    # 空でもOK、`answer`アクションで設定したインスタンス変数を使うため
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QuizApp</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%#= javascript_pack_tag 'application' %>
</head>

<body>
  <% if flash[:notice] %>
    <div class="alert alert-success"><%= flash[:notice] %></div>
  <% end %>
  <% if flash[:alert] %>
    <div class="alert alert-danger"><%= flash[:alert] %></div>
  <% end %>

  <%= yield %>
</body>
</html>

app/views/questions/index.html.erb
<%= stylesheet_link_tag 'questions_index', :media => "all" %>
<h1>クイズ一覧</h1>
<div class="quiz-container">
    <div class="filter">
        <%= form_with(url: questions_path, method: :get, local: true) do %>
            <%= select_tag :genre_id, options_from_collection_for_select(@genres, :id, :name), prompt: "全てのジャンル", class: "genre-select" %>
            <%= submit_tag "検索", class: "search-button" %>
        <% end %>
    </div>

    <ul class="quiz-list">
        <% @questions.each do |question| %>
            <li class="quiz-item">
                <%= link_to question.content, question_path(question), class: "quiz-link" %>
            </li>
        <% end %>
    </ul>
</div>

app/views/questions/reason.html.erb
<%= stylesheet_link_tag 'questions_reason', media: "all" %>
<h1 class="reason-title">回答理由を記入</h1>

<div class="reason-container">
    <p class="reason-prompt">あなたが「<%= @user_answer.upcase %>」を選んだ思考（理由）を教えてください。</p>

    <%= form_with url: answer_question_path(@question), method: :post do %>
        <div class="reason-field">
            <%= text_area_tag :reason, nil, placeholder: "理由を記入してください", class: "reason-input" %>
        </div>
        <%= hidden_field_tag :answer, @user_answer %>
        <div class="button-container">
            <%= submit_tag '回答結果を見る', class: 'submit-button' %>
        </div>
    <% end %>
</div>

app/views/questions/result.html.erb
<%= stylesheet_link_tag 'questions_result', media: "all" %>
<h1 class="result-title">回答結果</h1>

<div class="result-container">
    <% if @correct %>
        <p class="result-message correct">選択した回答は正解です！</p>
    <% else %>
        <p class="result-message incorrect">選択した回答は不正解です。正しい答えは「<%= @question.correct_answer.upcase %>」です。</p>
    <% end %>

    <div class="explanation-block">
        <p class="kaisetu-text"><strong>解説:</strong> <%= @question.kaisetu %></p>
    </div>
    <p>回答理由はご自身で合っているかどうかご確認ください</p>
    <div class="user-reason-block">
        <p class="user-reason">あなたの回答理由: <%= params[:reason].presence || "なし" %></p>
    </div>

    <div class="button-container">
        <%= link_to '他の問題へ', questions_path, class: 'next-button' %>
    </div>
</div>

app/views/questions/show.html.erb
<%= stylesheet_link_tag 'questions_show', media: "all" %>
<h1 class="question-title"><%= @question.content %></h1>

<%= form_with url: reason_question_path(@question), method: :get do %>
    <div class="answer-options">
        <div class="answer-option">
            <%= radio_button_tag 'answer', 'a', false, id: 'answer_a' %>
            <%= label_tag 'answer_a', @question.answer_a, class: 'answer-label' %>
        </div>
        <div class="answer-option">
            <%= radio_button_tag 'answer', 'b', false, id: 'answer_b' %>
            <%= label_tag 'answer_b', @question.answer_b, class: 'answer-label' %>
        </div>
    </div>
    <div class="button-container">
        <%= submit_tag '回答する', class: 'submit-button' %>
    </div>
<% end %>